Index: Makefile
===================================================================
--- Makefile	(revision 56)
+++ Makefile	(working copy)
@@ -57,6 +57,9 @@
 	core_math1.o core_math2.o core_phloat.o core_sto_rcl.o \
 	core_tables.o core_variables.o
 
+SRCS += core_aux.cc
+OBJS += core_aux.o
+
 ifdef BCD_MATH
 CXXFLAGS += -DBCD_MATH
 EXE = free42dec
